title: 小哲的个人导航网站   #网站标题
subTitle: 一个想赚钱的普通程序员
avatar: /logo.png

# 首页快速访问卡片
quickAccess:
  - name: vue
    description: 易学易用，性能出色，适用场景丰富的 Web 前端框架
    icon: https://cn.vuejs.org/logo.svg
    url: https://cn.vuejs.org/
  - name: react
    description: 用于构建 Web 和原生交互界面的库
    icon: https://react.docschina.org/favicon.ico
    url: https://react.docschina.org/
  - name: 掘金
    description: 一个很好的开发者社区，可以看看大佬的各种文章
    icon: https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web/static/favicons/favicon-32x32.png
    url: https://juejin.cn/
  - name: github
    description: 全球最大的开发者平台
    icon: https://github.githubassets.com/favicons/favicon.svg
    url: https://github.com/
  - name: 通义千问
    description: 阿里达摩院推出的大模型，拥有千亿参数，可用于智能问答、知识检索、文案创作等场景
    icon: https://acd-assets.alicdn.com/acd_work/tongyi-portal/assets/logo.svg
    url: https://www.tongyi.com/
  - name: Deepseek
    description: 深度求索（DeepSeek）
    icon: https://www.deepseek.com/favicon.ico
    url: https://chat.deepseek.com/
  - name: Snapdrop
    description: 局域网文件传输
    icon: https://drop.ioiox.com/images/favicon-96x96.png
    url: https://drop.ioiox.com/
  - name: HelloGithub
    description: 专注于发现和分享有趣、入门级的开源项目。在这里，探索开源技术解决方案，体验开源的乐趣，自荐或推荐开源项目，开启你的开源之旅。
    icon: https://hellogithub.com/favicon/favicon-32x32.png
    url: https://hellogithub.com/

# 首页底部的友情链接
friendLink:
  - name: 项目地址
    url: https://github.com/ConsoleLZ/GrowthGO
  - name: myBlog
    url: https://consolelz.github.io/
  - name: 掘金
    url: https://juejin.cn/user/1295692732053241


# 网站上线时间（这个会展示在统计页面的运行时长那里, 注意格式：xxxx-xx-xx xx:xx）
onlineTime: 2025-11-09

paginationValue: 24